version: 0.2

env:
  variables:
    DOCKER_REGISTRY_URL: /myapp/dockerhub/url
    DOCKER_REGISTRY_USERNAME: /myapp/dockerhub/username
    DOCKER_REGISTRY_PASSWORD: /myapp/dockerhub/password
    MY_APP_NAME: java-application
    MY_APP_VERSION: 1.0.0
    MY_APP_PORT: 8080


phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Docker...
      - cat /etc/os-release
      - apt-get update
      - apt-get install ca-certificates curl
      - sudo install -m 0755 -d /etc/apt/keyrings
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      - echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      - apt-get update
      - apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
      - echo Docker installed successfully.
  pre_build:
    commands:
      - echo Pre-build started on `date`
      - echo "Prebuild stage"
      - echo Pre-build completed on `date`
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USERNAME --password-stdin $DOCKER_REGISTRY_URL
      - echo Building the Docker image...
      - docker build -t $DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/$MY_APP_NAME:$MY_APP_VERSION prometheus/java-application/Dockefile
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/$MY_APP_NAME:$MY_APP_VERSION