version: 0.2

env:
  variables:
    DOCKER_REGISTRY_URL: /myapp/dockerhub/url
    DOCKER_REGISTRY_USERNAME: /myapp/dockerhub/username
    DOCKER_REGISTRY_PASSWORD: /myapp/dockerhub/password
    MY_APP_NAME: java-application
    MY_APP_VERSION: 1.0.0
    MY_APP_PORT: 8080


phases:
  pre_build:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USERNAME --password-stdin $DOCKER_REGISTRY_URL
      - echo Building the Docker image...
      - docker build -t $DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/$MY_APP_NAME:$MY_APP_VERSION prometheus/java-application/Dockefile
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/$MY_APP_NAME:$MY_APP_VERSION