global:
  scrape_interval:     5s
  evaluation_interval: 30s
scrape_configs:
- job_name: my-application
  honor_labels: true
  static_configs:
   - targets: ['python-application:5000','nodejs-application:5000']
  # - targets: ['go-application:5000','python-application:5000','dotnet-application:5000','nodejs-application:5000']
- job_name: 'java-application'
  honor_labels: true
  metrics_path: /actuator/prometheus
  scheme: http
  static_configs:
    - targets: ['java-application:8080']